import GeneratedTaskType from '../../types/GeneratedTaskType';

export class GetGeneratedUserTasksService {
  static generateTask(): GeneratedTaskType {
    const getRandomElement = <T>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

    const name = getRandomElement([
      'Write documentation',
      'Fix login bug',
      'Implement feature flag',
      'Design wireframes',
      'Refactor authentication logic',
      'Deploy to staging',
      'Set up CI/CD pipeline',
      'Update dependencies',
      'Write integration tests',
      'Prepare sprint demo',
    ]);
    const description = getRandomElement([
      'Auto-generated by AI.',
      'This is a placeholder task.',
      'Please review and update.',
      'High priority task.',
      'Optional refinement step.',
      '',
    ]);

    return {
      name,
      description,
    };
  }

  static generateTasks(count = 5): GeneratedTaskType[] {
    return Array.from({ length: count }, () => GetGeneratedUserTasksService.generateTask());
  }
}

export default GetGeneratedUserTasksService;
